version: "3.8"

services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_EMAIL_MODE=smtp
      - GENERIC_TIMEZONE=Europe/Stockholm
      - N8N_ENCRYPTION_KEY=digynex_secret_key_change_me
    volumes:
      - /root/.n8n:/home/node/.n8n

