/**
 * DigyNex PDF Engine (pdfService.js)
 * ================================================
 * ENGINE-FIRST ARCHITECTURE: This service is the SOLE gateway
 * for all PDF generation across the DigyNex platform.
 *
 * CURRENT ENGINE: Browser-native window.print() with custom @media print styles
 * PRODUCTION SWAP: Gotenberg.dev cloud endpoint (swap GOTENBERG_ENDPOINT below)
 *
 * Strict Rule: All components call this service — NEVER call print/fetch directly from UI.
 */

// ─── CONFIGURATION ───────────────────────────────────────────────
const GOTENBERG_ENDPOINT = null; // Set to 'https://your-gotenberg-instance/forms/chromium/convert/html' in production
const PDF_VERSION = 'V10.0';
const DIGYNEX_WATERMARK = 'Generated by DigyNex AI Job Finder';

// ─── CORE PDF ENGINE ──────────────────────────────────────────────

/**
 * generateFromHtml — Primary PDF generation method.
 * If Gotenberg endpoint is configured → uses cloud-based HD rendering.
 * If not → falls back to browser print engine (still professional quality).
 *
 * @param {string} htmlContent — Full HTML string of the CV
 * @param {string} fileName — Output filename (e.g. "Amila_CV_Elite.pdf")
 * @param {object} options — { tier, userName, primaryColor }
 * @returns {Promise<{success: boolean, method: string, error?: string}>}
 */
const generateFromHtml = async (htmlContent, fileName = 'DigyNex_CV.pdf', options = {}) => {
    const { tier = 0, userName = 'Candidate', primaryColor = '#0A2647' } = options;

    try {
        // PRODUCTION PATH: Gotenberg HD Rendering
        if (GOTENBERG_ENDPOINT) {
            return await _gotenbergGenerate(htmlContent, fileName, options);
        }

        // FALLBACK PATH: Browser Print Engine (Professional Quality)
        return await _browserPrintGenerate(htmlContent, fileName, { tier, userName, primaryColor });

    } catch (err) {
        console.error('[DigyNex PDF Engine] Critical failure:', err);
        return { success: false, method: 'error', error: err.message };
    }
};

// ─── GOTENBERG ENGINE (Production) ───────────────────────────────

const _gotenbergGenerate = async (htmlContent, fileName, options) => {
    console.log('[DigyNex PDF] Using Gotenberg HD Engine...');

    const formData = new FormData();
    const blob = new Blob([_wrapWithPrintStyles(htmlContent, options)], { type: 'text/html' });
    formData.append('files', blob, 'index.html');

    // A4 paper, zero margins for precision layout
    formData.append('paperWidth', '8.27');
    formData.append('paperHeight', '11.69');
    formData.append('marginTop', '0');
    formData.append('marginBottom', '0');
    formData.append('marginLeft', '0');
    formData.append('marginRight', '0');
    formData.append('preferCssPageSize', 'true');
    formData.append('printBackground', 'true');

    const response = await fetch(GOTENBERG_ENDPOINT, { method: 'POST', body: formData });

    if (!response.ok) throw new Error(`Gotenberg returned ${response.status}`);

    const pdfBlob = await response.blob();
    _triggerDownload(pdfBlob, fileName);

    return { success: true, method: 'gotenberg' };
};

// ─── BROWSER PRINT ENGINE (Working Fallback) ─────────────────────

const _browserPrintGenerate = async (htmlContent, fileName, options) => {
    console.log('[DigyNex PDF] Using Browser Print Engine...');

    return new Promise((resolve) => {
        // Create hidden iframe for isolated print context
        const iframe = document.createElement('iframe');
        iframe.style.cssText = 'position:fixed;top:-9999px;left:-9999px;width:794px;height:1123px;border:none;';
        document.body.appendChild(iframe);

        const doc = iframe.contentDocument || iframe.contentWindow.document;
        doc.open();
        doc.write(_wrapWithPrintStyles(htmlContent, options));
        doc.close();

        // Wait for resources to load, then trigger print
        iframe.onload = () => {
            setTimeout(() => {
                try {
                    // Set document title to control PDF filename in browser
                    const originalTitle = document.title;
                    document.title = fileName.replace('.pdf', '');

                    iframe.contentWindow.focus();
                    iframe.contentWindow.print();

                    // Restore title after print dialog
                    setTimeout(() => {
                        document.title = originalTitle;
                        document.body.removeChild(iframe);
                    }, 1000);

                    resolve({ success: true, method: 'browser-print' });
                } catch (err) {
                    document.body.removeChild(iframe);
                    resolve({ success: false, method: 'error', error: err.message });
                }
            }, 800);
        };
    });
};

// ─── HTML WRAPPER (Print-Optimized) ──────────────────────────────

const _wrapWithPrintStyles = (htmlContent, options = {}) => {
    const { primaryColor = '#0A2647', tier = 0, userName = 'Candidate' } = options;

    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DigyNex CV — ${userName}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@300;400;600;700;800;900&family=Playfair+Display:wght@900&display=swap" rel="stylesheet">
    <style>
        /* ── DIGYNEX PRECISION PRINT ENGINE V10.0 ── */
        *, *::before, *::after { box-sizing: border-box; -webkit-print-color-adjust: exact; print-color-adjust: exact; }

        @page {
            size: A4 portrait;
            margin: 0;
        }

        html, body {
            margin: 0;
            padding: 0;
            width: 210mm;
            min-height: 297mm;
            font-family: 'Plus Jakarta Sans', sans-serif;
            background: white;
            color: #1a1a1a;
        }

        /* Tier-based watermark */
        body::after {
            content: "${tier < 2 ? DIGYNEX_WATERMARK : ''}";
            display: ${tier < 2 ? 'block' : 'none'};
            position: fixed;
            bottom: 8mm;
            right: 8mm;
            font-size: 6pt;
            color: rgba(0,0,0,0.15);
            font-family: 'Plus Jakarta Sans', sans-serif;
            letter-spacing: 0.1em;
            text-transform: uppercase;
        }

        @media print {
            body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
        }
    </style>
</head>
<body>
    ${htmlContent}
</body>
</html>`;
};

// ─── DOWNLOAD TRIGGER (for Blob/Gotenberg) ───────────────────────

const _triggerDownload = (blob, fileName) => {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = fileName;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
};

// ─── FILENAME GENERATOR ───────────────────────────────────────────

const buildFileName = (userName = 'Candidate', templateName = 'Elite') => {
    const cleanName = userName.trim().replace(/\s+/g, '_');
    const date = new Date().toISOString().slice(0, 10);
    return `${cleanName}_DigyNex_${templateName}_${date}.pdf`;
};

// ─── PDF ENGINE STATUS ────────────────────────────────────────────

const getEngineStatus = () => ({
    mode: GOTENBERG_ENDPOINT ? 'gotenberg-hd' : 'browser-print',
    gotenbergReady: !!GOTENBERG_ENDPOINT,
    version: PDF_VERSION,
    watermarkActive: true, // disabled for Tier 2
});

const exportSpecimen = (htmlContent, fileName = 'Specimen.html') => {
    const blob = new Blob([htmlContent], { type: 'text/html' });
    _triggerDownload(blob, fileName);
};

// ─── EXPORTS ─────────────────────────────────────────────────────

export const pdfService = {
    generateFromHtml,
    buildFileName,
    getEngineStatus,
    exportSpecimen,
};
